language: java

dist: trusty

jdk:
  - oraclejdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_407f38382059_key -iv $encrypted_407f38382059_iv
    -in src/test/resources/secrets.tar.enc -out ./secrets.tar -d
  - tar xvf secrets.tar

env:
  global:
    - GCP_EMAIL=unittest@embulk-input-gcs-test.iam.gserviceaccount.com
    - GCP_BUCKET=embulk-input-gcs-test
    - GCP_BUCKET_DIRECTORY=unittests_import
    - GCP_P12_KEYFILE=./embulk-input-gcs-test-40bbfa15acd2.p12
    - GCP_JSON_KEYFILE=./embulk-input-gcs-test-2492bb6e0f66.json

script:
  - ./gradlew gem
  - ./gradlew --info check jacocoTestReport
