language: java

jdk:
  - oraclejdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_79f1af2a2546_key -iv $encrypted_79f1af2a2546_iv
    -in src/test/resources/secretkeys.tar.enc -out secretkeys.tar -d
  - tar xvf secretkeys.tar

env:
  global:
    - GCP_EMAIL=unittest@embulk-input-gcs-test.iam.gserviceaccount.com
    - GCP_BUCKET=embulk-input-gcs-test
    - GCP_BUCKET_DIRECTORY=unittests_import
    - GCP_P12_KEYFILE=./embulk-input-gcs-test-018324286daf.p12
    - GCP_JSON_KEYFILE=./embulk-input-gcs-test-841948b819cf.json

script:
  - ./gradlew gem
  - ./gradlew --info check jacocoTestReport
