name: Build and test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up OpenJDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: "temurin"
      - name: Test
        env:
          GCP_EMAIL: ${{secrets.GCP_EMAIL}}
          GCP_JSON_KEYFILE: ${{secrets.GCP_JSON_KEYFILE}}
          GCP_PRIVATE_KEYFILE: ${{secrets.GCP_PRIVATE_KEYFILE}}
          GCP_BUCKET: ${{secrets.GCP_BUCKET}}
          GCP_BUCKET_DIRECTORY: ${{secrets.GCP_BUCKET_DIRECTORY}}
        run: ./gradlew --stacktrace test
